version: '3.8'

services:
  # 🔹 Cassandra Multi-Node Setup
  cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ClickstreamCluster

  cassandra2:
    image: cassandra
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1
    depends_on:
      - cassandra1

  # 🔹 Zookeeper (for Kafka)
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # 🔹 Kafka Broker
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  # 🔹 Prometheus for Monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # 🔹 Grafana for Visualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # 🔹 Golang Backend Service
  clickstream-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickstream-api
    ports:
      - "8080:8080"
    depends_on:
      - cassandra1
      - kafka
